- shell:
   - mkdir -p ~/.{config/{git,fish},ssh,darcs}
- link:
   # OS X
   ~/Library/KeyBindings/DefaultKeyBinding.dict: Library/KeyBindings/DefaultKeyBinding.dict
   # shells
   ~/.profile: profile
   ~/.inputrc: inputrc
   ~/.shrc: shrc
   ~/.profile.d: profile.d/
   ~/.config/fish/config.fish: config/fish/config.fish
   ~/.config/fish/functions: config/fish/functions/
   # Git
   ~/.config/git/config: config/git/config
   ~/.config/git/ignore: config/git/ignore
   ~/.gitflow_export: gitflow_export
   # editors
   ~/.emacs.d: emacs.d/
   ~/.spacemacs: spacemacs.el
   ~/.vimrc: vimrc
   # other assorted software
   ~/.ssh/config: ssh/config
   ~/.darcs/author: darcs/author
   ~/.clisprc.lisp: clisprc.lisp
   ~/.cmucl-init.lisp: cmucl-init.lisp
   ~/.sbclrc: sbclrc
